### ISSUE TITLE
Failed to Create/Open: xception_pascalvoc.pb

### ISSUE THREAD

**Issue by bluetooth-mdw** [ayoolaolafenwa/PixelLib#43]
Hello,

I'm new to PixelLib and have just installed it, following the instructions in the official documentation. I'm using Windows 10 with Python 3.7.3.

What I run theis example: https://gist.github.com/ayoolaolafenwa/019448eb8693337c5e7c70a08041b801#file-image_detect_person-py

I get the following error. Is a file missing?

```
Traceback (most recent call last):
  File "blur_person.py", line 5, in <module>
    change_bg.load_pascalvoc_model("xception_pascalvoc.pb")
  File "C:\Python37\lib\site-packages\pixellib\tune_bg.py", line 32, in load_pascalvoc_model
    graph_def = tf.compat.v1.GraphDef.FromString(file_handle.read())
  File "C:\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "C:\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: xception_pascalvoc.pb : The system cannot find the file specified.
```

**Comment by ayoolaolafenwa** [comment]
Download the model from [here](https://github.com/ayoolaolafenwa/PixelLib/releases/download/1.1/xception_pascalvoc.pb)

**Comment by bluetooth-mdw** [comment]
Thank you

**Comment by hadati** [comment]
thank you
