### ISSUE TITLE
Opencv !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by Adblu** [ayoolaolafenwa/PixelLib#55]
Im Trying to execute:

```
change_bg.change_video_bg(single_vid, "bg.jpg", frames_per_second=10, output_video_name=output_vid + new_vid,
                          detect="car")
```

However im getting following error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/snap/pycharm-professional/240/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/240/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/n/Documents/Background_removal/src/pixellib_main_vid.py", line 18, in <module>
    detect="car")
  File "/home/n/anaconda3/envs/background/lib/python3.7/site-packages/pixellib/tune_bg.py", line 301, in change_video_bg
    img = cv2.resize(img, (h,w))
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-hj027r8z/opencv/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

What might be the cause of it ?

**Comment by Adblu** [comment]
```"bg.jpg"``` background image should not be static, or should be better documented.
