### ISSUE TITLE
Unable to load model during image segmentation

### ISSUE THREAD

**Issue by alic-xc** [ayoolaolafenwa/PixelLib#68]
HI guys,
I'm having trouble during loading of model.  
```
WARNING:tensorflow:From /Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:605: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
2021-06-02 15:28:25.934049: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "/Users/aladelekan/Documents/testsegment/test-detect.py", line 15, in <module>
    segment_image.load_model("mask_rcnn_model.h5")
  File "/Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/pixellib/instance.py", line 60, in load_model
    self.model.load_weights(model_path, by_name= True)
  File "/Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/pixellib/mask_rcnn.py", line 2111, in load_weights
    hdf5_format.load_weights_from_hdf5_group_by_name(f, layers)
  File "/Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 788, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #221 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 324) dtype=float32> has shape (1024, 324), but the saved weight has shape (1024, 8).

Process finished with exit code 1

```

any help will be appreciated.

**Comment by ayoolaolafenwa** [comment]
@alic-xc Share the code you used for inference.

**Comment by alic-xc** [comment]
After i've trained my model. i tried instance segmentation which gave me error.

```
import os

import pixellib
from pixellib.instance import instance_segmentation
segment_image = instance_segmentation()
segment_image.load_model("mask_rcnn_coco.h5")
segment_image.segmentImage("earlyFingerling111.jpg", show_bboxes = True, output_image_name = "image_new.jpg")

```

```
WARNING:tensorflow:From /Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:605: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
2021-06-05 08:40:47.395083: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "test-detect.py", line 16, in <module>
    segment_image.load_model("mask_rcnn_coco.h5")
  File "/Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/pixellib/instance.py", line 60, in load_model
    self.model.load_weights(model_path, by_name= True)
  File "/Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/pixellib/mask_rcnn.py", line 2111, in load_weights
    hdf5_format.load_weights_from_hdf5_group_by_name(f, layers)
  File "/Users/aladelekan/.local/share/virtualenvs/testsegment-3avR_sav/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 788, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #221 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 324) dtype=float32> has shape (1024, 324), but the saved weight has shape (1024, 8).

```

**Comment by ayoolaolafenwa** [comment]
@alic-xc  you used the wrong code for inference.  This is the code for performing inference with your custom trained model.
``` python
import pixellib
from pixellib.instance import custom_segmentation

segment_image = custom_segmentation()
#inference configuration for your cutom model to state  the number of classes and class names
#change it to your trained model configuration
segment_image.inferConfig(num_classes= 2, class_names= ["BG", "butterfly", "squirrel"])
segment_image.load_model("mask_rcnn_model/Nature_model_resnet101.h5")
segment_image.segmentImage("sample2.jpg", show_bboxes=True) 
```
Read my [tutorial](https://github.com/ayoolaolafenwa/PixelLib/blob/master/Tutorials/custom_inference.md) on performing inference with custom models.
