### ISSUE TITLE
ValueError: Tensor Tensor("mrcnn_detection/Reshape_1:0", shape=(1, 100, 6), dtype=float32) is not an element of this graph

### ISSUE THREAD

**Issue by fanweiya** [ayoolaolafenwa/PixelLib#69]
I use flask and PixelLib to do an web application, but report such an error. Do you know what the error?
```
Traceback (most recent call last):
  File "F:\Anaconda\envs\tf2\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Anaconda\envs\tf2\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Anaconda\envs\tf2\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Anaconda\envs\tf2\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "F:\Anaconda\envs\tf2\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Anaconda\envs\tf2\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "group_detection_flask.py", line 81, in predict
    segmask, output = segment_frame.segmentImage(input_path, show_bboxes=True,extract_segmented_objects=True,verbose=1)
  File "F:\Anaconda\envs\tf2\lib\site-packages\pixellib\instance.py", line 569, in segmentImage
    results = self.model.detect([new_img])
  File "F:\Anaconda\envs\tf2\lib\site-packages\pixellib\mask_rcnn.py", line 2465, in detect
    self.keras_model.predict([molded_images, image_metas, anchors], verbose=0)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 728, in predict
    callbacks=callbacks)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 571, in _make_execution_function
    return model._make_execution_function(mode)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2131, in _make_execution_function
    self._make_predict_function()
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2121, in _make_predict_function
    **kwargs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3769, in function
    return GraphExecutionFunction(inputs, outputs, updates=updates, **kwargs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3421, in __init__
    with ops.control_dependencies([self.outputs[0]]):
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5159, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 4583, in control_dependencies
    c = self.as_graph_element(c)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3505, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "F:\Anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3584, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("mrcnn_detection/Reshape_1:0", shape=(1, 100, 6), dtype=float32) is not an element of this graph.
```

**Comment by step305** [comment]
My solution is to run detection in separate process (using multiprocessing). Communication with this "worker" process is done using queues. In this case Flask web app runs without errors.
